// Code generated by mockery. DO NOT EDIT.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Anton119/rocket-service-/order/internal/model"
	"github.com/Anton119/rocket-service-/order/internal/service/input"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type OrderService
func (_mock *OrderService) CancelOrder(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, id interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, id)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(err error) *OrderService_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type OrderService
func (_mock *OrderService) CreateOrder(ctx context.Context, in input.CreateOrderInput) (*input.CreateOrderResult, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *input.CreateOrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.CreateOrderInput) (*input.CreateOrderResult, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.CreateOrderInput) *input.CreateOrderResult); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*input.CreateOrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.CreateOrderInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.CreateOrderInput
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, in interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, in)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, in input.CreateOrderInput)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.CreateOrderInput
		if args[1] != nil {
			arg1 = args[1].(input.CreateOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(createOrderResult *input.CreateOrderResult, err error) *OrderService_CreateOrder_Call {
	_c.Call.Return(createOrderResult, err)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, in input.CreateOrderInput) (*input.CreateOrderResult, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type OrderService
func (_mock *OrderService) GetOrder(ctx context.Context, id uuid.UUID) (model.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OrderService_Expecter) GetOrder(ctx interface{}, id interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(order model.Order, err error) *OrderService_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Order, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function for the type OrderService
func (_mock *OrderService) PayOrder(ctx context.Context, in input.PayOrderInput) (uuid.UUID, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PayOrderInput) (uuid.UUID, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.PayOrderInput) uuid.UUID); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.PayOrderInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.PayOrderInput
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, in interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, in)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, in input.PayOrderInput)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.PayOrderInput
		if args[1] != nil {
			arg1 = args[1].(input.PayOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(uUID uuid.UUID, err error) *OrderService_PayOrder_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, in input.PayOrderInput) (uuid.UUID, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
