// Code generated by mockery. DO NOT EDIT.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Anton119/rocket-service-/inventory/internal/model"
	"github.com/Anton119/rocket-service-/inventory/internal/service/input"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewPartService creates a new instance of PartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartService {
	mock := &PartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartService is an autogenerated mock type for the PartService type
type PartService struct {
	mock.Mock
}

type PartService_Expecter struct {
	mock *mock.Mock
}

func (_m *PartService) EXPECT() *PartService_Expecter {
	return &PartService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type PartService
func (_mock *PartService) GetPart(ctx context.Context, id uuid.UUID) (model.Part, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Part, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Part); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type PartService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PartService_Expecter) GetPart(ctx interface{}, id interface{}) *PartService_GetPart_Call {
	return &PartService_GetPart_Call{Call: _e.mock.On("GetPart", ctx, id)}
}

func (_c *PartService_GetPart_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PartService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_GetPart_Call) Return(part model.Part, err error) *PartService_GetPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartService_GetPart_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (model.Part, error)) *PartService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type PartService
func (_mock *PartService) ListParts(ctx context.Context, in input.ListPartsInput) ([]model.Part, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ListPartsInput) ([]model.Part, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, input.ListPartsInput) []model.Part); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, input.ListPartsInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type PartService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - in input.ListPartsInput
func (_e *PartService_Expecter) ListParts(ctx interface{}, in interface{}) *PartService_ListParts_Call {
	return &PartService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, in)}
}

func (_c *PartService_ListParts_Call) Run(run func(ctx context.Context, in input.ListPartsInput)) *PartService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 input.ListPartsInput
		if args[1] != nil {
			arg1 = args[1].(input.ListPartsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_ListParts_Call) Return(parts []model.Part, err error) *PartService_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartService_ListParts_Call) RunAndReturn(run func(ctx context.Context, in input.ListPartsInput) ([]model.Part, error)) *PartService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
