syntax = "proto3";

package payment.v1;

option go_package = "github.com/Anton119/rocket-service-/shared/pkg/proto/payment/v1;paymentv1";

import "buf/validate/validate.proto";

// PaymentService обрабатывает оплату заказов
service PaymentService {
  // PayOrder — оплата заказа, в ответе transaction_uuid
  rpc PayOrder(PayOrderRequest) returns (PayOrderResponse);
}

// Способ оплаты
enum PaymentMethod {
  // не указан
  PAYMENT_METHOD_UNSPECIFIED = 0;
  // банковская карта
  PAYMENT_METHOD_CARD = 1;
  // СБП
  PAYMENT_METHOD_SBP = 2;
  // кредитная карта
  PAYMENT_METHOD_CREDIT_CARD = 3;
  // деньги инвестора
  PAYMENT_METHOD_INVESTOR_MONEY = 4;
}

// Запрос PayOrder
message PayOrderRequest {
  // UUID заказа (обязательный)
  string order_uuid = 1 [(buf.validate.field).string.uuid = true];
  // способ оплаты (обязательный, без UNSPECIFIED)
  PaymentMethod payment_method = 2 [(buf.validate.field).enum = { not_in: [0] }];
}

// Ответ PayOrder
message PayOrderResponse {
  // UUID транзакции оплаты
  string transaction_uuid = 1;
}
